development:
  secret_key_base: super_long_secret_key_for_development
  google_client_id: 206704832754-53ii91fjorsi4su9nfjsoptfc5a00r0t.apps.googleusercontent.com
  google_client_secret: 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
